# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\n./messages',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\"\xca\x01\n\x0b\x43limateData\x12\x15\n\rUTC_TIMESTAMP\x18\x01 \x01(\x03\x12\x11\n\tLONGITUDE\x18\x02 \x01(\x02\x12\x10\n\x08LATITUDE\x18\x03 \x01(\x02\x12\x17\n\x0f\x41IR_TEMPERATURE\x18\x04 \x01(\x02\x12\x15\n\rPRECIPITATION\x18\x05 \x01(\x02\x12\x17\n\x0fSOLAR_RADIATION\x18\x06 \x01(\x02\x12\x1b\n\x13SURFACE_TEMPERATURE\x18\x07 \x01(\x02\x12\x19\n\x11RELATIVE_HUMIDITY\x18\x08 \x01(\x03\"@\n\rAggregateData\x12\x16\n\x0e\x41GGREGATE_NAME\x18\x01 \x01(\t\x12\x17\n\x0f\x41GGREGATE_VALUE\x18\x02 \x01(\x02\"`\n\x07Wrapper\x12$\n\x0c\x63limate_data\x18\x01 \x01(\x0b\x32\x0c.ClimateDataH\x00\x12(\n\x0e\x61ggregate_data\x18\x02 \x01(\x0b\x32\x0e.AggregateDataH\x00\x42\x05\n\x03msgB\x0cZ\n./messagesb\x06proto3'
)




_CLIMATEDATA = _descriptor.Descriptor(
  name='ClimateData',
  full_name='ClimateData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='UTC_TIMESTAMP', full_name='ClimateData.UTC_TIMESTAMP', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LONGITUDE', full_name='ClimateData.LONGITUDE', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LATITUDE', full_name='ClimateData.LATITUDE', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AIR_TEMPERATURE', full_name='ClimateData.AIR_TEMPERATURE', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PRECIPITATION', full_name='ClimateData.PRECIPITATION', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SOLAR_RADIATION', full_name='ClimateData.SOLAR_RADIATION', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SURFACE_TEMPERATURE', full_name='ClimateData.SURFACE_TEMPERATURE', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RELATIVE_HUMIDITY', full_name='ClimateData.RELATIVE_HUMIDITY', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=220,
)


_AGGREGATEDATA = _descriptor.Descriptor(
  name='AggregateData',
  full_name='AggregateData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='AGGREGATE_NAME', full_name='AggregateData.AGGREGATE_NAME', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AGGREGATE_VALUE', full_name='AggregateData.AGGREGATE_VALUE', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=286,
)


_WRAPPER = _descriptor.Descriptor(
  name='Wrapper',
  full_name='Wrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='climate_data', full_name='Wrapper.climate_data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aggregate_data', full_name='Wrapper.aggregate_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='Wrapper.msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=288,
  serialized_end=384,
)

_WRAPPER.fields_by_name['climate_data'].message_type = _CLIMATEDATA
_WRAPPER.fields_by_name['aggregate_data'].message_type = _AGGREGATEDATA
_WRAPPER.oneofs_by_name['msg'].fields.append(
  _WRAPPER.fields_by_name['climate_data'])
_WRAPPER.fields_by_name['climate_data'].containing_oneof = _WRAPPER.oneofs_by_name['msg']
_WRAPPER.oneofs_by_name['msg'].fields.append(
  _WRAPPER.fields_by_name['aggregate_data'])
_WRAPPER.fields_by_name['aggregate_data'].containing_oneof = _WRAPPER.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['ClimateData'] = _CLIMATEDATA
DESCRIPTOR.message_types_by_name['AggregateData'] = _AGGREGATEDATA
DESCRIPTOR.message_types_by_name['Wrapper'] = _WRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClimateData = _reflection.GeneratedProtocolMessageType('ClimateData', (_message.Message,), {
  'DESCRIPTOR' : _CLIMATEDATA,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:ClimateData)
  })
_sym_db.RegisterMessage(ClimateData)

AggregateData = _reflection.GeneratedProtocolMessageType('AggregateData', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATEDATA,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:AggregateData)
  })
_sym_db.RegisterMessage(AggregateData)

Wrapper = _reflection.GeneratedProtocolMessageType('Wrapper', (_message.Message,), {
  'DESCRIPTOR' : _WRAPPER,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Wrapper)
  })
_sym_db.RegisterMessage(Wrapper)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
